import { User, Post, Job, Connection } from '../types';

export const currentUser: User = {
  id: '1',
  name: 'Sarah Johnson',
  title: 'Senior Product Manager',
  company: 'TechCorp',
  location: 'San Francisco, CA',
  avatar: '👩‍💼',
  banner: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&h=300&fit=crop',
  connections: 847,
  about: 'Experienced product manager with a passion for building innovative solutions that improve user experiences. Specializing in SaaS products, agile methodologies, and cross-functional team leadership.',
  skills: ['Product Management', 'Agile', 'User Research', 'Data Analysis', 'Leadership', 'Strategy', 'Roadmapping', 'A/B Testing'],
  experience: [
    {
      id: '1',
      title: 'Senior Product Manager',
      company: 'TechCorp',
      location: 'San Francisco, CA',
      startDate: 'Jan 2021',
      endDate: null,
      description: 'Leading product strategy and development for enterprise SaaS platform serving 50K+ users.',
    },
    {
      id: '2',
      title: 'Product Manager',
      company: 'StartupXYZ',
      location: 'New York, NY',
      startDate: 'Jun 2018',
      endDate: 'Dec 2020',
      description: 'Managed product lifecycle for mobile application with 1M+ downloads.',
    },
  ],
  education: [
    {
      id: '1',
      school: 'Stanford University',
      degree: 'MBA',
      field: 'Business Administration',
      startYear: '2016',
      endYear: '2018',
    },
    {
      id: '2',
      school: 'UC Berkeley',
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      startYear: '2012',
      endYear: '2016',
    },
  ],
};

export const posts: Post[] = [
  {
    id: '1',
    author: {
      name: 'Michael Chen',
      title: 'CEO at InnovateLab',
      avatar: '👨‍💼',
    },
    content: 'Excited to announce that our team has just launched our new AI-powered analytics platform! This has been 2 years in the making, and I\'m incredibly proud of what we\'ve built. Check it out and let me know what you think! 🚀',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop',
    likes: 234,
    comments: 45,
    shares: 12,
    timeAgo: '2h',
  },
  {
    id: '2',
    author: {
      name: 'Emily Rodriguez',
      title: 'UX Designer at DesignHub',
      avatar: '👩‍🎨',
    },
    content: '5 key principles I\'ve learned about user-centered design:\n\n1. Always validate assumptions with real users\n2. Iterate early and often\n3. Design for accessibility from day one\n4. Less is more - simplify, simplify, simplify\n5. Data should inform, not dictate decisions\n\nWhat would you add to this list?',
    likes: 567,
    comments: 89,
    shares: 34,
    timeAgo: '5h',
  },
  {
    id: '3',
    author: {
      name: 'David Kim',
      title: 'Software Engineer at CloudScale',
      avatar: '👨‍💻',
    },
    content: 'Just published a new article on microservices architecture patterns! Link in the comments. Would love to hear your thoughts and experiences.',
    likes: 189,
    comments: 23,
    shares: 8,
    timeAgo: '1d',
  },
  {
    id: '4',
    author: {
      name: 'Lisa Anderson',
      title: 'VP of Marketing at BrandWorks',
      avatar: '👩‍💼',
    },
    content: 'Thrilled to share that our Q4 campaign exceeded all expectations! Grateful to work with such an amazing team. Success is always a team effort. 🎉',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    likes: 445,
    comments: 56,
    shares: 19,
    timeAgo: '2d',
  },
];

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Senior Product Manager',
    company: 'Meta',
    location: 'Menlo Park, CA',
    type: 'Full-time',
    level: 'Senior',
    postedDate: '2 days ago',
    applicants: 87,
    description: 'Lead product strategy for next-generation social features',
    logo: '🔵',
  },
  {
    id: '2',
    title: 'Full Stack Engineer',
    company: 'Google',
    location: 'Mountain View, CA',
    type: 'Full-time',
    level: 'Mid-Senior',
    postedDate: '3 days ago',
    applicants: 142,
    description: 'Build scalable cloud infrastructure solutions',
    logo: '🔴',
  },
  {
    id: '3',
    title: 'UX Design Lead',
    company: 'Apple',
    location: 'Cupertino, CA',
    type: 'Full-time',
    level: 'Senior',
    postedDate: '5 days ago',
    applicants: 63,
    description: 'Shape the future of user experiences across Apple products',
    logo: '🍎',
  },
  {
    id: '4',
    title: 'Data Scientist',
    company: 'Amazon',
    location: 'Seattle, WA',
    type: 'Full-time',
    level: 'Mid-Level',
    postedDate: '1 week ago',
    applicants: 201,
    description: 'Drive insights from data to improve customer experiences',
    logo: '📦',
  },
  {
    id: '5',
    title: 'Marketing Manager',
    company: 'Salesforce',
    location: 'San Francisco, CA',
    type: 'Full-time',
    level: 'Mid-Senior',
    postedDate: '1 week ago',
    applicants: 94,
    description: 'Lead marketing initiatives for enterprise products',
    logo: '☁️',
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'Netflix',
    location: 'Los Gatos, CA',
    type: 'Full-time',
    level: 'Senior',
    postedDate: '2 weeks ago',
    applicants: 156,
    description: 'Optimize streaming infrastructure at global scale',
    logo: '🎬',
  },
];

export const connections: Connection[] = [
  {
    id: '1',
    name: 'Alex Thompson',
    title: 'Software Engineer',
    company: 'Microsoft',
    avatar: '👨‍💻',
    mutualConnections: 23,
  },
  {
    id: '2',
    name: 'Jessica Lee',
    title: 'Product Designer',
    company: 'Adobe',
    avatar: '👩‍🎨',
    mutualConnections: 15,
  },
  {
    id: '3',
    name: 'Robert Martinez',
    title: 'Engineering Manager',
    company: 'Tesla',
    avatar: '👨‍🔧',
    mutualConnections: 31,
  },
  {
    id: '4',
    name: 'Amanda Wilson',
    title: 'Data Analyst',
    company: 'Airbnb',
    avatar: '👩‍💼',
    mutualConnections: 12,
  },
  {
    id: '5',
    name: 'Chris Brown',
    title: 'Marketing Director',
    company: 'Spotify',
    avatar: '👨‍💼',
    mutualConnections: 28,
  },
  {
    id: '6',
    name: 'Sophia Garcia',
    title: 'HR Manager',
    company: 'LinkedIn',
    avatar: '👩‍💼',
    mutualConnections: 19,
  },
];

export const suggestions: Connection[] = [
  {
    id: '7',
    name: 'Daniel Park',
    title: 'Senior Developer',
    company: 'Stripe',
    avatar: '👨‍💻',
    mutualConnections: 8,
  },
  {
    id: '8',
    name: 'Olivia Taylor',
    title: 'Product Manager',
    company: 'Uber',
    avatar: '👩‍💼',
    mutualConnections: 5,
  },
  {
    id: '9',
    name: 'James Anderson',
    title: 'CTO',
    company: 'TechStart',
    avatar: '👨‍💼',
    mutualConnections: 11,
  },
];
